package com.redhat.fsi.creditcarddisputecase;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class FraudData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Integer lineItemCount;
	private java.lang.Integer maxDaysElapsed;
	private Float totalFraudAmount;
	private boolean automated;
	private java.lang.String customerStatus;
	private java.lang.Integer disputeRiskRating;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "FRAUDDATA_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "FRAUDDATA_ID_GENERATOR", sequenceName = "FRAUDDATA_ID_SEQ")
	private java.lang.Long id;

	private java.lang.String caseId;

	public FraudData() {
	}

	public java.lang.Integer getLineItemCount() {
		return this.lineItemCount;
	}

	public void setLineItemCount(java.lang.Integer lineItemCount) {
		this.lineItemCount = lineItemCount;
	}

	public java.lang.Integer getMaxDaysElapsed() {
		return this.maxDaysElapsed;
	}

	public void setMaxDaysElapsed(java.lang.Integer maxDaysElapsed) {
		this.maxDaysElapsed = maxDaysElapsed;
	}

	public FraudData(java.lang.Float totalFraudAmount,
			java.lang.Integer lineItemCount, java.lang.Integer maxDaysElapsed,
			boolean automated, java.lang.String customerStatus) {
		this.totalFraudAmount = totalFraudAmount;
		this.lineItemCount = lineItemCount;
		this.maxDaysElapsed = maxDaysElapsed;
		this.automated = automated;
		this.customerStatus = customerStatus;
	}

	public boolean isAutomated() {
		return this.automated;
	}

	public void setAutomated(boolean automated) {
		this.automated = automated;
	}

	public java.lang.String getCustomerStatus() {
		return this.customerStatus;
	}

	public void setCustomerStatus(java.lang.String customerStatus) {
		this.customerStatus = customerStatus;
	}

	public java.lang.Integer getDisputeRiskRating() {
		return this.disputeRiskRating;
	}

	public void setDisputeRiskRating(java.lang.Integer disputeRiskRating) {
		this.disputeRiskRating = disputeRiskRating;
	}

	@Override
	public String toString() {
		return "FraudData [lineItemCount=" + lineItemCount
				+ ", maxDaysElapsed=" + maxDaysElapsed + ", totalFraudAmount="
				+ totalFraudAmount + ", automated=" + automated
				+ ", customerStatus=" + customerStatus + ", disputeRiskRating="
				+ disputeRiskRating + "]";
	}

	public java.lang.Float getTotalFraudAmount() {
		return this.totalFraudAmount;
	}

	public void setTotalFraudAmount(java.lang.Float totalFraudAmount) {
		this.totalFraudAmount = totalFraudAmount;
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getCaseId() {
		return this.caseId;
	}

	public void setCaseId(java.lang.String caseId) {
		this.caseId = caseId;
	}

	public FraudData(java.lang.Integer lineItemCount,
			java.lang.Integer maxDaysElapsed, java.lang.Float totalFraudAmount,
			boolean automated, java.lang.String customerStatus,
			java.lang.Integer disputeRiskRating, java.lang.Long id,
			java.lang.String caseId) {
		this.lineItemCount = lineItemCount;
		this.maxDaysElapsed = maxDaysElapsed;
		this.totalFraudAmount = totalFraudAmount;
		this.automated = automated;
		this.customerStatus = customerStatus;
		this.disputeRiskRating = disputeRiskRating;
		this.id = id;
		this.caseId = caseId;
	}

}
