package com.redhat.fsi.creditcarddisputecase;
import org.jbpm.casemgmt.api.model.instance.*;
import java.util.HashMap;
import java.util.Map;

rule "Manager Approval Required" ruleflow-group "manager-approval-check"

when
    $caseData : CaseFileInstance(data.get("managerApprovalRequired") == null)
    FraudData(totalFraudAmount > 1000) from $caseData.getData("fraudData")
    
then
    System.out.println("In the then section of the rules");
    $caseData.add("managerApprovalRequired", true);
end
    
    
rule "Associate fraud data with case"

when
    $caseData : CaseFileInstance(data.get("fraudData") == null)
    $fraudData : FraudData(caseId == null) from $caseData.getData("fraudData")
    
then
    System.out.println("Associating froud data with case " + $caseData.getCaseId());
    $fraudData.setCaseId($caseData.getCaseId());
end    