package com.redhat.fsi.creditcarddisputecase;
import org.jbpm.casemgmt.api.model.instance.*;
import java.util.HashMap;
import java.util.Map;

rule "Manager Approval Required" ruleflow-group "manager-approval-check"

when
    $caseData : CaseFileInstance(data.get("managerApprovalRequired") == null)
    FraudData(totalFraudAmount > 1000) from $caseData.getData("fraudData")
    
then
    System.out.println("In the then section of the rules");
    $caseData.add("managerApprovalRequired", true);
end
